### PR TITLE
Prettified and fixed keyboard controls

### PR DESCRIPTION
**Pull request by MuhsinFatih**
I was wandering around your code and saw the keyboard control code and
realized it's not working. Made it work and couldn't stop myself from
making it look cool! :) use W A S D for movement and Q E for zoom and R
for reset camera. I made some transition effect which I am sure you will
like :thumbsup: .
I also added "draw object path" toggle since I was annoyed by the people
around me not understanding that the moon on the app actually does a
pretty nice orbit around earth. I think removing the path line being an
option helps better visualize the thing.

One last thing: I couldn't exactly figure out how the renderGrid
function works so I couldn't touch it so I had to set the grid toggle to
unchecked by default (which if you ask me looks better :smile:
especially with the zoom in at startup effect). What happens is that
when I zoom in or out, grid shifts like crazy and disturbs my eyes. I
hope you can rewrite that function later on.

### CODE REVIEW

**Comment by MuhsinFatih** [comment]
By the way, I am not sure if I requested pull correctly. Some say bringing fork up to date by merging latest changes from master can mess things up. If so, please let me know how I can fix it.

**Comment by HermannBjorgvin** [comment]
Sweet! Merged to master. Sorry about gui.js btw, it started out fine but it's the stuff of nightmares by now.

Might rewrite the whole render/gui thing and add stuff like touch control and such, the gui was kind of an afterthought when I first made the sim.

**Comment by HermannBjorgvin** [comment]
Fixed the issue with the grid, going to add touch input functionality before updating the live site.

**Comment by MuhsinFatih** [comment]
great! btw I just saw that blackhole thing commented and man thats so awesome, couldn't stop playing with it like a couple hours ^^ but that asteroid belt with 1000 objects even with my 2015 model macbook pro it drops down to 10 fps 😄

**Comment by HermannBjorgvin** [comment]
Hey can you maybe comment your code and variable for the stuff that you did to the camera? Trying to work out a bug where the game stalls if there isn't an object with cameraFocus=true

**Comment by MuhsinFatih** [comment]
Sorry I am outside now. Hopefully I will comment when I get back home. Maybe we can even do some skype talk to work on it, that way I can better explain stuff

**Comment by MuhsinFatih** [comment]
well, it was an exhausting day and I got sick so couldn't do it yet sorry. Give me a couple days I will do it when I get chance

**Comment by HermannBjorgvin** [comment]
No rush, my skype is: hermannbh if you want to chat

**Comment by MuhsinFatih** [comment]
man I am very sorry that I forgot to comment on my code, my life is busy as hell right now so I forget a ton of things. Apparently you have fixed it already tho. I really apologize

**Comment by HermannBjorgvin** [comment]
No worries, development is pretty slow and I just do things in bursts when I feel like it. I'm replacing the GUI and Render modules right now for a common thing.

Cheers

**Pull request merged**
