### PR TITLE
Updated Position of new Joined Object

### PR DESCRIPTION
**Pull request by scchow**
Weighted the new (x,y) position by mass contribution of each object rather than momentum

Also rewrote the for loops going through each object so that it doesn't
iterate through spacetime backwards. (A stylistic choice.)

### CODE REVIEW

**Comment by scchow** [comment]
Hmm, I thought I created a pull request with this chain. I'm relatively new to Github so I'm not quite sure how everything works yet. How do you submit a pull request?

**Comment by HermannBjorgvin** [comment]
Looks like you're working on the same code as PluckerPluck https://github.com/HermannBjorgvin/Gravity-Experiments/compare/master...Pluckerpluck:patch-2

Github is complaining about some conflicts between the two, it look like you're doing the exact same thing though.

**Comment by Pluckerpluck** [comment]
1) Counting down is a TINY bit faster (one less bytecode instruction). Please don't write it backwards just for this though, forward tends to be clearer and the overhead is nothing in an application like this. Just thought I'd throw out some information.

2) Yeah, this is now a cleaned up version of mine. I kept your styling, but I'd suggest looking at @scchow's here and changing yours to match.

newV = (v*m + V*M)/(m+M)

is clearer than

newV = v*m/(m+M) + V*M/(m+M)

in terms of what's physically happening.

3) @scchow: If you add the URL of the issue in the pull request then a link to the pull request appears in the issue. Very useful to do.

Like: Solves issue https://github.com/HermannBjorgvin/Gravity-Experiments/issues/1

**Comment by scchow** [comment]
@Pluckerpluck 
1) Oh, that's very interesting. Never realized there was a difference. Learn something new everyday.
3) Oh I see, thank you for the advice.

**Comment by scchow** [comment]
It seems like the master branch has already been updated with the changes I made in this pull request, going to close it for now.

**Pull request closed without merging**
