### PR TITLE
Position of combined object moved

### PR DESCRIPTION
**Pull request by Pluckerpluck**
Objects should probably join towards their centre of mass. This works off just pure mass, not momentum. The rest looks fine. You don't conserve energy in collisions.

https://github.com/HermannBjorgvin/Gravity-Experiments/issues/1

### CODE REVIEW

**Comment by Pluckerpluck** [comment]
Erm... I'm a little special. Do the same for the y coordinate.

**Comment by HermannBjorgvin** [comment]
Looks solid, merged with master

**Comment by Pluckerpluck** [comment]
ABORT ABORT!

Look at the y coordinate! Uses objectB not A for the first part. My bad... Simple fix, just stupid mistake

Edit: Pull request https://github.com/HermannBjorgvin/Gravity-Experiments/compare/master...Pluckerpluck:patch-2

**Comment by HermannBjorgvin** [comment]
Will do.

**Pull request merged**
