### PR TITLE
Right click mass option

### PR DESCRIPTION
**Pull request by MuhsinFatih**
Allow the user to determine the mass of the auto-orbiting object (Right click to initiate, left click to release)
By the way, sorry for the "lines that look like changed but are not" confusion if happened. You had mixed tabs and spaces, my editor decided to tabify :)

### CODE REVIEW

**Comment by HermannBjorgvin** [comment]
Cool changes. Could you change it so that it's right click for both initiate and release though? It's a bit unintuitive to go from right click to left click. Otherwise it looks good, will merge it to master branch

Cheers

**Comment by MuhsinFatih** [comment]
@HermannBjorgvin 
Ok, I have done it :)
In fact, I didn't know I was actually updating the pull request after every commit to branch (this is my first-ever contribution to someone else's project on Github :) ) Changes kinda looks like messy now. So I would like to summarize changes here:
1. Allow the user to determine the mass of the auto-orbiting object. (This time with a checkbox for this option. I added that checkbox because since we call the right click method "easy", it would better be fixed mass by default so the user can add a bunch of masses quickly as before which is sometimes more fun :) )
2. Added a cancel mechanism: When the user left clicks for example, right mouse button means nothing until the mass is released. So the right mouse button could be used for cancelling the operation.
3. Added right-click functionality for backwards "cycle object focus". Useful when you have a lot of objects :)
4. Fixed the crash when trying to create an auto-orbiting object after clearing spacetime.

Edit: Oh, and i changed it to "right click to release" for auto-orbit as you said.

**Comment by HermannBjorgvin** [comment]
Sweet. Don't worry about the commits.

Happy new year!

**Comment by HermannBjorgvin** [comment]
Updated live website from master branch with your changes.

**Comment by HermannBjorgvin** [comment]
Alright, was going to fix a tiny bug in your code (auto orbiting objects don't scale with zoom) but I found myself infuriated by my GUI module (was supposed to be a temporary fix). Going to tear it apart during the weekend and fix this shit, dirty spaghetti code that's impossible to traverse.

**Comment by MuhsinFatih** [comment]
Thanks a lot for merging!
What do you mean auto orbiting objects don't scale with zoom? And also, yeah, sorry about auto-formatting. I regularly format the code so your code was also formatted with my ide's style. But I can revert the rest of the code formatting if you like. If you mean the code, not the formatting though, I can try to tidy it up if you like.

**Comment by MuhsinFatih** [comment]
Are you sure you merged this properly to the live website? It works fine when I download the repository to desktop and open index.html in chrome. In the live website, however, right click custom mass option does not work at all.

**Comment by HermannBjorgvin** [comment]
Works for me on firefox, are you sure you got "custom mass on right click" enabled?

Also I was talking about the GUI.js module I created, initially I created it as a temporary test suite for doing stuff with the spacetime module but since then it has spun into a place of chaos and despair. I tried to find the reason why your auto orbiter wasn't scaling a custom mass with zoom but I couldn't put my finger on it

Will probably rewrite it this weekend, maybe add touch stuff like pinch zoom etc etc

**Comment by MuhsinFatih** [comment]
It works on firefox on my pc as well, but on chrome it acts like i didn't check the custom mass option. But when I download repository and open the website locally, it works both on chrome and firefox. I also uploaded it to my raspberry pi server and tried it there, it works on server as well. I don't know, there's something wrong. Check it on chrome, you will understand what I'm saying

**Comment by HermannBjorgvin** [comment]
Actually works perfectly for me on Chrome version 47. Maybe it's your version of Chrome that's outdated?

**Comment by MuhsinFatih** [comment]
No it's version 47.0.2526.106. I just realized that only on chrome on my machine it doesn't work. It works on other browsers and all the other computers in home. I don't know why this happens. I also cleaned cookies but still buggy. Even in incognito mode it works. Perhaps it's chrome's bug on my pc. Anyways, even if it's not, it will probably get fixed when you rewrite the code as you said.
Happy new year btw :)

**Comment by HermannBjorgvin** [comment]
Try to clear your cache

**Pull request merged**
